arguments:
    criteria:
        - ordersCount
        - externalId
        - createdAt

options:
    crmUrl: 'https://example.com'
    apiKey: 'apikeystring'
    fields: 'id,phones,externalId,firstName,lastName,email,ordersCount'
    importantFields: 'customField.cedula,birthday'

    all-sites: true
    no-cache: true
    csv: true